AWSTemplateFormatVersion: "2010-09-09"
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
  
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.0.0/24
  
  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
  
  InternetGateway:
    Type: AWS::EC2::InternetGateway
  
  GatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
  
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
  
  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: GatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
  
  NatGateway1EIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
  
  NatGateway1:
    Type: AWS::EC2::NatGateway
    Properties:
      SubnetId: !Ref PublicSubnet
      AllocationId: !GetAtt NatGateway1EIP.AllocationId
  
  NatGateway2EIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
  
  NatGateway2:
    Type: AWS::EC2::NatGateway
    Properties:
      SubnetId: !Ref PublicSubnet
      AllocationId: !GetAtt NatGateway2EIP.AllocationId
  
  AuroraCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora
      EngineMode: provisioned
      EngineVersion: 5.7.mysql_aurora.2.07.2
      MasterUsername: admin
      MasterUserPassword: Password123
      DBSubnetGroupName: !Ref PrivateSubnetGroup
      AvailabilityZones:
        - us-east-1a
        - us-east-1b
      StorageEncrypted: true
  
  AuroraReadReplica:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: aurora
      EngineVersion: 5.7.mysql_aurora.2.07.2
      DBClusterIdentifier: !Ref AuroraCluster
      DBInstanceIdentifier: aurora-read-replica
      DBInstanceClass: db.t3.small
      AvailabilityZone: us-east-2a
      PubliclyAccessible: false
  
  PrivateSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Private subnet group
      SubnetIds:
        - !Ref PrivateSubnet
